### ISSUE TITLE
Angular Pattern

### ISSUE THREAD

**Issue by eduardobvale** [alexander-elgin/angular-relative-day#2]
Hi guys, i noticed my JS compiler couldnt resolve the dependencies, so i did this modification:

```
.filter('relativeDay',['$locale', 'RelativeDayList' , function ($locale, RelativeDayList) {
```

Is it interesting to you?

**Comment by sijio** [comment]
Hello Eduardo,

Yes, thanks? Can you create a pull request?

Kind regards,
Alex

Eduardo Braz do Vale notifications@github.com wrote:

Hi guys, i noticed my JS compiler couldnt resolve the dependencies, so i did this modification:

.filter('relativeDay',['$locale', 'RelativeDayList' , function ($locale, RelativeDayList) {
Is it interesting to you?

**Comment by eduardobvale** [comment]
I did here:

https://github.com/alexander-elgin/angular-relative-day/pull/3

Hope it helps!
